### ISSUE TITLE
multiple time errors when compiling

### ISSUE THREAD

**Issue by jonathoncain** [fehlfarbe/terraesp#2]
I'm getting multiple time errors when compiling. specifically to deal with time.
[errors.txt](https://github.com/fehlfarbe/terraesp/files/6014123/errors.txt)

**Comment by fehlfarbe** [comment]
Hi!
Did you try the master branch? I updated many things in [version2](https://github.com/fehlfarbe/terraesp/tree/version2 ) branch.

**Comment by jonathoncain** [comment]
Yes I tried it first and was getting errors when compiling as well. I can
send the errors from that as well when I get home. It was right at the
beginning of the compiling. It was dealing with the feature/stage said it
wasnt in the upper stream or something like that.

**Comment by jonathoncain** [comment]
I wanted to clarify my earlier response. Version2 is the one I was having the errors on. I uploaded a copy of the terminal output.

**Comment by fehlfarbe** [comment]
Could be related to this problem: https://community.platformio.org/t/build-error-if-time-library-is-installed/450/6

I'm working on Linux so I can't really test it but I fixed some includes and I hope it will compile now.

**Comment by jonathoncain** [comment]
its still failing with fewer errors. 
[errors2.txt](https://github.com/fehlfarbe/terraesp/files/6017058/errors2.txt)

**Comment by fehlfarbe** [comment]
I updated some imports and added a note for Windows users:

> Windows users: if you get errors like `error: 'timeinfo' has incomplete type` just delete the `Time.h` header in `.pio/libdeps/{ota,usb}/Time`. The bug happens only on Windows because it's not case-sensitive and mixes the `time.h` header with `Time.h` of TimeLib library.

It's a problem of the TimeLib dependency and the `Time.h` header will be removed in the future. After deleting `Time.h` it compiles on Windows.

**Comment by jonathoncain** [comment]
The code is compiling without issue now. However it will not upload it says to specify upload port which I tried to add to the .ini file and have had no luck. It's like it doesn't recognize the board. If I create a new project and select the doit board version it uploads the blink sketch just fine so I don't know what the issue is

**Comment by fehlfarbe** [comment]
Hey sorry for my late response. Did you select the USB environment in platformio?

You can also delete the OTA environment if you don't use OTA.:
```
[env:ota]
build_flags = -D RELEASE
upload_protocol = espota
upload_port = terraesp.local
upload_flags =
    --auth=admin
```

**Comment by jonathoncain** [comment]
i figured it out it compiles and uploads. but when using the pio run -t uploadfs i get and error in the terminal windows that opens. i have attached the errors.
[error.txt](https://github.com/fehlfarbe/terraesp/files/6094764/error.txt)

**Comment by fehlfarbe** [comment]
I added `mklittlefs.exe` to the project that should enable LittleFS build for Windows. Please pull and try again :)

**Comment by jonathoncain** [comment]
thank you for all the help. its working now

**Comment by fehlfarbe** [comment]
You're welcome! Feel free to open a new issue if you need more help.
